version: '3.5'

services:

    backend:
      build: ../material-applications/example-backend
      environment:
        - POSTGRES_HOST=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=asd
        - REDIS_HOST=redis
      ports:
        - 8080:8080
      depends_on:
        - db
      container_name: backend_with_db

    db:
      image: postgres:13.2-alpine
      restart: unless-stopped
      environment:
        - POSTGRES_PASSWORD=asd
      
      volumes:
        - ./database:/var/lib/postgresql/data
      container_name: db-container

    frontend:
      build: ../material-applications/example-frontend
      ports:
        - 5000:5000
      container_name: frontend

    redis:
      image: "redis:alpine"
      container_name: redis




