version: '3.5'

services:

  frontend:
    build: ./ml-kurkkumopo-frontend
    ports:
      - 3000:3000
    container_name: frontend


  backend:
    build: ./ml-kurkkumopo-backend
    ports:
      - 5000:5000
    container_name: backend

    volumes:
      - model_volume:/src/model


  training:
    build: ./ml-kurkkumopo-training
    container_name: training
    volumes:
      - model_volume:/src/model
      - images:/src/imgs
      - data:/src/data

volumes:
  model_volume:
  images:
  data:
