version: '3.5'

services:
    frontend:
      build: ../../../material-applications/example-frontend
      ports:
        - 5000:5000
      container_name: example-frontend-2
     

    backend:
      build: ../../../material-applications/example-backend
      ports:
        - 8080:8080
      environment:
        - REDIS_HOST=redis
      container_name: exapmle-backend-2

    redis:
      image: "redis:alpine"
      container_name: redis
